### ISSUE TITLE
use context manager for more pythonic code?

### ISSUE THREAD

**Issue by kalikaneko** [radare/radare2-r2pipe-api#14]
I'm trying to think about how the usage of the python library can be made cleaner.

I'm hesitant about this proposal, but it occurred to me that using context managers for the ``R2Api`` objects would give a cleaner usage pattern, at least for short interactions:

For instance, the main api instantiation It would look something like this:

```
with open_in_radare('/bin/ls') as bin:
  if bin.is_stripped:
    print "this binary is stripped"
 searchIn(bin, 'io.sections.exec')
 analyzeCalls(bin)
```

basically this avoids having to manually quit() the api object - but it makes code indentated. I find it more readable this way tho. what do you think, is it worthy to explore this? maybe the change makes more sense with some other objects instead.

**Comment by quim0** [comment]
The `with as` idea really likes me.
The problem with `bin.is_stripped` is that radare2 can be used for a lot of things, not just binary analisis. 
The other problem is that you can have multiple files opened in radare, so in my opinion the `with as` must "open" radare sessions, not files, as you can have many files opened in a r2 session. 
That's why the idea was to create different objects, maybe something better could be:

``` python
with r2session('/bin/ls') as s: # Open a new session (r2 process)
  if s.info.is_stripped:
    print "this binary is stripped"
  s.analyze.calls()
# Close session (quit r2 process)
```
